### ISSUE TITLE
Schema Maker

### ISSUE THREAD

**Issue by nextdev1111** [zernonia/supabase-schema#10]
Can you please make a schema maker where we just the diagram and your website automatically generates the database for us. Isn't it possible.

**Comment by zernonia** [comment]
Hey @nextdev1111 , I don't quite understand 
> make a schema maker where we just the diagram 

What exact feature you are looking for ya?

**Comment by nextdev1111** [comment]
I was looking for a website where I can draw my sql schema diagrams and the website will generate a sql code for me. **I can just copy and paste it.**

**Comment by zernonia** [comment]
I know that this tool exist, [drawSQL](https://drawsql.app/) which does exactly what you wanted 😁
