### ISSUE TITLE
Light theme for the screenshot

### ISSUE THREAD

**Issue by kbsali** [zernonia/supabase-schema#4]
Thanks for this really cool app! :)

While I like a lot the default dark theme, I think it would be cool to be able to switch to a light theme, at least for taking the screenshot of the diagram to make it printable.

Thanks!

**Comment by zernonia** [comment]
I think it will be better and easier if the whole apps can toggle dark/light mode. 
especially utilizing tailwindcss's `dark` utility.

PR is welcome!! 🤩

**Comment by kbsali** [comment]
I wish I could take the time to learn a bit of vue.js to propose a PR :grimacing:

**Comment by zernonia** [comment]
@kbsali  it's ok ya.. thanks for commenting on this issue and I think I could work this out during this weekend..

**Comment by kbsali** [comment]
:heart_eyes: awesome! Now I can print the diagram!!!

**Comment by kbsali** [comment]
It works great! There is a tiny little bug though : when switching from dark to light theme, the linking grey lines don't show. Refreshing the page fixes the issue. :)
