### ISSUE TITLE
Array column type

### ISSUE THREAD

**Issue by josemasf** [zernonia/supabase-schema#7]
When you do an export of a table schema and one of the columns is of type text array, the array type is lost and it is left as simply array

When using the script, we receive a syntax error with the word ARRAY

**Example:**

![image](https://user-images.githubusercontent.com/24436751/153749927-a93da00f-165a-4685-9604-59e147afc0f9.png)

create table candidates ( id uuid default uuid_generate_v4() primary key, created_at timestamp default now(), name text, email text, phone text, entry text, tag text, status text, quizzes json, file text, "level" text, profilesJobs ARRAY, notes ARRAY );

**Comment by zernonia** [comment]
Hi @josemasf , this is a known issue as at this moment because the REST endpoint returning ARRAY, you need to manually update the "ARRAY" into the type you want.
