### ISSUE TITLE
"Export Types" fails for self-referencing foreign key

### ISSUE THREAD

**Issue by kbsali** [zernonia/supabase-schema#8]
I have a self-referencing foreign key on one of my tables (concretely `category.parent_id`),
the diagram shows it perfectly, but exporting to types fails (memory leak?).

**Comment by zernonia** [comment]
Hi again @kbsali  ! 😂  
Thank you so much for reporting this issue. 

Could you perhaps share a screenshot of the diagram, and a snapshot after you click export types? Appreciate it!

**Comment by kbsali** [comment]
Here is before adding the self ref foreign key : 
![image](https://user-images.githubusercontent.com/53676/155482168-1609a3a2-4a8b-4ed3-bbae-51f51d47aaee.png)

And after : 
![image](https://user-images.githubusercontent.com/53676/155482497-91577715-677d-46d6-b9f9-175e1d1d7f1d.png)

Not sure about the "snapshot after you click export", it just won't work! :grimacing:

**Comment by zernonia** [comment]
Thank you so much for the input! Yeah this could be memory leak due to self referencing infinitely.

**Comment by kbsali** [comment]
awesome, thank YOU for being so reactive on that one! :)

**Comment by lh15** [comment]
The export buttons are failing for me without a self referencing foreign key. The page crashes. 

I haven't been able to debug the issue.

<img width="839" alt="Screen Shot 2022-05-26 at 11 13 47 PM" src="https://user-images.githubusercontent.com/23442414/170641610-e551c848-c6c3-49e1-a4d9-0669fa7993b3.png">
